#!/usr/bin/env bash
#Bash script that displays time for 12hrs and 59 mins

hour=0

while [ $hour -le 12 ]
do
echo "Hour: $hour"

minute=1

while [ $minute -le 59 ]
do
echo "$minute"
(( minute++ ))
done
(( hour++ ))
done
