#!/usr/bin/env bash
#Bash script that displays:
# 'To infinity and beyond' indefinitely and with a 'sleep 2' in between

trap 'echo "I am invincible!!!"' SIGTERM
while true
do
echo "To infinity and beyond"
sleep 2
done
